### ISSUE TITLE
parse_darknet_yolo2.py

### ISSUE THREAD

**Issue by gengmujian10** [ruiminshen/yolo-tf#8]
INFO:tensorflow:yolo2_darknet/conv20/BatchNorm/moving_variance: [1024]=1024
<class 'numpy.int32'>
INFO:tensorflow:yolo2_darknet/conv20/weights: [3, 3, 3072, 1024]=28311552
<class 'numpy.int32'>
Traceback (most recent call last):
  File "parse_darknet_yolo2.py", line 137, in <module>
    main()
  File "parse_darknet_yolo2.py", line 94, in main
    p = struct.unpack('%df' % cnt, f.read(4 * cnt))
struct.error: unpack requires a bytes object of length 113246208

I print the value of(4*cnt). It actually equals to 113246208, and the type of cnt is int32.
And I do not know how to solve this problem.....
Could anyone tell me about it ?
Thank you !

**Comment by huseinzol05** [comment]
@ruiminshen not really follow the real model YOLOv2 architecture

**Comment by simo23** [comment]
Hi, 
@gengmujian10 did you check your python version? The author stated that he used python 3 so that could be the problem. I had the same issue in a similar case while unpacking some binary values and it was my wrong version of python.
@huseinzol05 could you please state why do you think this is wrong? I m trying to implement YOLOv2, I already made the forward as you did but I cannot find a valid training part. 
Thanks,
Andrea

**Comment by huseinzol05** [comment]
based on .cfg from darknet

[route]
layers=-9

[convolutional]
batch_normalize=1
size=1
stride=1
pad=1
filters=64
activation=leaky

from inference.py,
```python
_net = reorg(passthrough)
```
supposed,
```python
passthrough = slim.layers.conv2d(passthrough, 64)
_net = reorg(passthrough)
```

**Comment by Liberus** [comment]
so is there a solution for this problem?

**Comment by ashleyjsands** [comment]
I think I encountered this problem and I believe I got around the problem by downloading and using the `yolo-full.weights` file stored in the [Google Drive link](https://drive.google.com/drive/folders/0B1tW_VtY7onidEwyQ2FtQVplWEU).
